/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author 11852346914
 */
public class EscolhaAtributos extends javax.swing.JFrame {
    //interface para o jogador escolher o atributo a rodada
    private Carta carroJogador;

    /**
     * Creates new form EscolhaAtributos
     */
    public EscolhaAtributos(Carta c1) {
        carroJogador = c1;
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Peso = new javax.swing.JButton();
        Potencia = new javax.swing.JButton();
        VelMax = new javax.swing.JButton();
        Cilindradas = new javax.swing.JButton();
        Comprimento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Peso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Peso.setText("Peso");
        Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoActionPerformed(evt);
            }
        });

        Potencia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Potencia.setText("Potência");
        Potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotenciaActionPerformed(evt);
            }
        });

        VelMax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VelMax.setText("Velocidade Máxima");
        VelMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelMaxActionPerformed(evt);
            }
        });

        Cilindradas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cilindradas.setText("Cilindradas");
        Cilindradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CilindradasActionPerformed(evt);
            }
        });

        Comprimento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Comprimento.setText("Comprimento");
        Comprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cilindradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Peso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Potencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Comprimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cilindradas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Comprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoActionPerformed
        dispose();
        Jogo.proseguir(Jogo.PcEscolherCarta("none"), carroJogador, "Peso");
    }//GEN-LAST:event_PesoActionPerformed

    private void PotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotenciaActionPerformed
        dispose();
        Jogo.proseguir(Jogo.PcEscolherCarta("none"), carroJogador, "Potencia");
    }//GEN-LAST:event_PotenciaActionPerformed

    private void VelMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelMaxActionPerformed
        dispose();
        Jogo.proseguir(Jogo.PcEscolherCarta("none"), carroJogador, "Velocidade");
    }//GEN-LAST:event_VelMaxActionPerformed

    private void CilindradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CilindradasActionPerformed
        dispose();
        Jogo.proseguir(Jogo.PcEscolherCarta("none"), carroJogador, "Cilindradas");
    }//GEN-LAST:event_CilindradasActionPerformed

    private void ComprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprimentoActionPerformed
        dispose();
       Jogo.proseguir(Jogo.PcEscolherCarta("none"), carroJogador, "Comprimento");
    }//GEN-LAST:event_ComprimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaAtributos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaAtributos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaAtributos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaAtributos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaAtributos(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cilindradas;
    private javax.swing.JButton Comprimento;
    private javax.swing.JButton Peso;
    private javax.swing.JButton Potencia;
    private javax.swing.JButton VelMax;
    // End of variables declaration//GEN-END:variables
}
