/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.util.Random;
import javax.swing.JTextPane;

/**
 *
 * @author Bruno Galeazzi Rech
 */
public class PainelJogador extends javax.swing.JFrame {

    /**
     * Creates new form PainelJogador
     */
    private String atributoDaVez;

    public PainelJogador() {
        initComponents();
        setLocationRelativeTo(null);
        c[0] = c1;
        c[1] = c2;
        c[2] = c3;
        c[3] = c4;
        c[4] = c5;
        if (Jogo.vezDeQuem.equalsIgnoreCase("inicio")) {//primeira rodada
            Random r = new Random();
            if (r.nextInt(2) == 0) {
                Jogo.vezDeQuem = "jogador";
            } else {
                Jogo.vezDeQuem = "Pc";
            }
        }  
        
        if (Jogo.vezDeQuem.equalsIgnoreCase("jogador")) {//rodada do jogador
            Jogo.pescarCartas("jogador");
            Jogo.pescarCartas("pc");
            lb_atributo.setText("Você é quem escolhe o atributo nessa rodada");
            Jogo.vezDeQuem = "Pc";
            carregarCartas();
        } else if (Jogo.vezDeQuem.equalsIgnoreCase("Pc")) {//rodada do computador
            Jogo.pescarCartas("pc");
            Jogo.pescarCartas("jogador");
            atributoDaVez = Jogo.PcEscolherAtributo();
            Jogo.vezDeQuem = "jogador";
            lb_atributo.setText("Escolha uma carta e boa sorte!");
            carregarCartas();

        }
        checarMao("jogador");
        checarMao("pc");
        
        //para testes:
      /*  System.out.println("------------------------------------------------------------------------------------------");
        for (int i=0;i<5;i++){
            if (Jogo.maoComputador.get(i) != null)
            System.out.println(Jogo.maoComputador.get(i).getNome());
            
        }
        System.out.println("");
        for (int i=0;i<5;i++){
             if (Jogo.maoJogador.get(i) != null)
            System.out.println(Jogo.maoJogador.get(i).getNome());
            
        }
                System.out.println("------------------------------------------------------------------------------------------");
        */
    }

    private void checarMao(String player) {//verificação se os jogadores ainda possuem cartas na mão
        if (player.equalsIgnoreCase("jogador")) {
            if (c[0].getText().equalsIgnoreCase("") && c[1].getText().equalsIgnoreCase("") && c[2].getText().equalsIgnoreCase("") &&
                    c[3].getText().equalsIgnoreCase("") && c[4].getText().equalsIgnoreCase("")) {
                System.out.println("acabou");
                //fazer um fim
            }
        } else if (player.equalsIgnoreCase("pc")) {
            /*if (Jogo.maoComputador.get(0).toString().equalsIgnoreCase("") && Jogo.maoComputador.get(1).toString().equalsIgnoreCase("") &&
                    Jogo.maoComputador.get(2).toString().equalsIgnoreCase("") &&
                    Jogo.maoComputador.get(3).toString().equalsIgnoreCase("") &&
                    Jogo.maoComputador.get(4).toString().equalsIgnoreCase("")) {
                   System.out.println("pc perdeu");
                   //fazer 1 fim
            }*/
        }
    }

    private void carregarCartas() {//carrega as informações das cartas na tela do jogador
        for (int i = 0; i < 5; i++) {
            try {
                c[i].setText(Jogo.maoJogador.get(i).toString());
            } catch (Exception e) {
                c[i].setText("");
            }
        }

    }

    private void conferirVez(int i) {//método auxiliar
        if (lb_atributo.getText().equalsIgnoreCase("Você é quem escolhe o atributo nessa rodada")) {
            new EscolhaAtributos(Jogo.maoJogador.remove(i)).setVisible(true);
            Jogo.idMaoJ.push(i);
        } else {
            Jogo.proseguir(Jogo.PcEscolherCarta(atributoDaVez), Jogo.maoJogador.remove(i), atributoDaVez);
            Jogo.idMaoJ.push(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt4 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        c4 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        c3 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        c2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        c5 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        c1 = new javax.swing.JTextPane();
        lb_atributo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bt4.setText("Escolher");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt1.setText("Escolher");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setText("Escolher");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setText("Escolher");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt5.setText("Escolher");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        c4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jScrollPane1.setViewportView(c4);

        c3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jScrollPane2.setViewportView(c3);

        c2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jScrollPane3.setViewportView(c2);

        c5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jScrollPane4.setViewportView(c5);

        c1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jScrollPane5.setViewportView(c1);

        lb_atributo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lb_atributo.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))))
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(lb_atributo, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt2)
                    .addComponent(bt3)
                    .addComponent(bt1)
                    .addComponent(bt4)
                    .addComponent(bt5))
                .addGap(18, 18, 18)
                .addComponent(lb_atributo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        if (!c[0].getText().equalsIgnoreCase("")) {
            dispose();
            conferirVez(0);

        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        if (!c[3].getText().equalsIgnoreCase("")) {
            dispose();
            conferirVez(3);
        }
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        if (!c[1].getText().equalsIgnoreCase("")) {
            dispose();
            conferirVez(1);
        }
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        if (!c[2].getText().equalsIgnoreCase("")) {
            dispose();
            conferirVez(2);
        }
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        if (!c[4].getText().equalsIgnoreCase("")) {
            dispose();
            conferirVez(4);
        }
    }//GEN-LAST:event_bt5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelJogador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JTextPane c1;
    private javax.swing.JTextPane c2;
    private javax.swing.JTextPane c3;
    private javax.swing.JTextPane c4;
    private javax.swing.JTextPane c5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lb_atributo;
    // End of variables declaration//GEN-END:variables
    private JTextPane[] c = new JTextPane[5];
}
